name 'agate-php'
version '0.0.1'
source 'git://github.com/leventyalcin/agate-php.git'
author 'Levent Yalcin'
license 'Apache 2.0'
summary 'php Module'
description 'php install with custom package name'
project_page 'git://github.com/leventyalcin/agate-php'
